### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by tanmay777** [princebansal/MyVIT#5]
Search Faculty
Apply for Leave
Faculty message
Upcoming event
Exam Schedule
Marks
Course Page
Changing password
Campus map need to be improved.
Order of Grades in grade summary
Digital Assignment 
VIT Academics Calendar
Service Request for transcript, transport etc
Exam Schedule
Mess Change
Registration for Physical Education eg. Swimming, badminton
CGPA Calculator
Paper Seeing, Paper Reevaluation

**Comment by Ramkishorevit** [comment]
Tanmay put everything as different issues. So that it can be assigned and distributed to all and be closed.

**Comment by tanmay777** [comment]
ohkay! (Y)
